table FactInternetSales
	lineageTag: 1953fc49-3b0f-4a5f-b1cc-04ca545f49ce
	sourceLineageTag: [dbo].[FactInternetSales]

	measure 'Sales Amount' = ```
			
			SUMX(
			    'FactInternetSales',
			    'FactInternetSales'[OrderQuantity] * 'FactInternetSales'[UnitPrice]
			) 
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 7e818f5c-88cc-4698-bfad-34d17cccaf21

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: b4d4e047-f073-42b7-a6b8-59ddd69b008e
		sourceLineageTag: ProductKey
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column OrderDateKey
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 2f763ec2-7cbb-4d4d-ad30-6cf4b570d858
		sourceLineageTag: OrderDateKey
		summarizeBy: none
		sourceColumn: OrderDateKey

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column DueDateKey
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 799a6249-e205-4257-b9b4-7d21e9481097
		sourceLineageTag: DueDateKey
		summarizeBy: none
		sourceColumn: DueDateKey

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column ShipDateKey
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: a23af6ea-1a1d-441e-8234-6b90848c51c9
		sourceLineageTag: ShipDateKey
		summarizeBy: none
		sourceColumn: ShipDateKey

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 08f540fd-d5dc-49b4-9d3a-652cd87d9019
		sourceLineageTag: CustomerKey
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column SalesOrderNumber
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 7183c0ae-bfb5-4020-b180-46c61cd158b1
		sourceLineageTag: SalesOrderNumber
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: 1a1080fd-e815-445d-946f-802d78a7c5bb
		sourceLineageTag: OrderQuantity
		summarizeBy: none
		sourceColumn: OrderQuantity

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column UnitPrice
		dataType: double
		sourceProviderType: decimal(19, 4)
		lineageTag: cef56185-a4b5-435d-962d-b633ada81d95
		sourceLineageTag: UnitPrice
		summarizeBy: none
		sourceColumn: UnitPrice

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitPriceDiscountPct
		dataType: double
		sourceProviderType: float
		lineageTag: 6beb0361-a0fb-44f4-bb1e-35cdfd80caf4
		sourceLineageTag: UnitPriceDiscountPct
		summarizeBy: none
		sourceColumn: UnitPriceDiscountPct

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductStandardCost
		dataType: double
		sourceProviderType: decimal(19, 4)
		lineageTag: ac8578dc-6d29-4439-82b9-42a12962219b
		sourceLineageTag: ProductStandardCost
		summarizeBy: none
		sourceColumn: ProductStandardCost

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FactInternetSales = entity
		mode: directLake
		source
			entityName: FactInternetSales
			schemaName: dbo
			expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table

