table FactInternetSales
	lineageTag: f62a2690-8bf0-4026-88bf-b617da7153d5

	measure 'Sales Amount' =
			
			SUMX(
			    'FactInternetSales',
			    'FactInternetSales'[OrderQuantity] * 'FactInternetSales'[UnitPrice]
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 911c56b2-e3e7-45a1-9134-31b121f4204a

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1dec10cb-d4aa-4c5c-b371-604e2e812e70
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5503b258-c8b9-4ba7-809d-cff6f18dd121
		summarizeBy: none
		sourceColumn: OrderDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column DueDateKey
		dataType: int64
		formatString: 0
		lineageTag: 91c05a66-97c6-43b9-8c2d-36104c4d4545
		summarizeBy: none
		sourceColumn: DueDateKey

		annotation SummarizationSetBy = User

	column ShipDateKey
		dataType: int64
		formatString: 0
		lineageTag: 237ea96b-c527-45ae-b52c-fbb71bee26cc
		summarizeBy: none
		sourceColumn: ShipDateKey

		annotation SummarizationSetBy = User

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b9e1c507-f20b-4922-b916-16e93f8d6136
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesOrderNumber
		dataType: string
		lineageTag: d025a98a-ef70-4827-8395-b60c3f6caeb7
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		lineageTag: 39bd5afb-60b7-4d78-9012-77265262271a
		summarizeBy: none
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = User

	column UnitPrice
		dataType: double
		lineageTag: 2b07cbb8-0196-4e33-a309-3a0f822e79f3
		summarizeBy: none
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitPriceDiscountPct
		dataType: double
		lineageTag: d42cca9c-5e75-45ba-8241-c0010a9b40d8
		summarizeBy: none
		sourceColumn: UnitPriceDiscountPct

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductStandardCost
		dataType: double
		lineageTag: f0c114e6-d677-4be3-9b9f-66b9aa0c6b60
		summarizeBy: none
		sourceColumn: ProductStandardCost

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FactInternetSales = m
		mode: import
		source =
				let
				    Source = Sql.Database(Server, Database),
				    dbo_FactInternetSales = Source{[Schema="dbo",Item="FactInternetSales"]}[Data]
				in
				    dbo_FactInternetSales

	annotation PBI_ResultType = Table

